### ISSUE TITLE
test: useAnalyzedResume + useDownloadPdf suites fail locally (13) — localStorage global shadows jsdom, trips pre-push verify

### ISSUE THREAD

**Issue by s-annam** [offlinecv/OfflineCV#398]
## Summary

Two hook test suites fail locally on a clean `main` (13 tests), tripping the local pre-push `verify` hook and the Claude Stop hook:

- `src/hooks/useAnalyzedResume.test.tsx` (9 failures)
- `src/hooks/useDownloadPdf.test.tsx` (4 failures)

They are **unrelated to any current PR** — confirmed by stashing all working changes on a clean `main` checkout: still 13 failed. Neither suite imports recently-changed files. Surfaced while landing batch #396 (PR #397), which had to push with `RESUMELINT_SKIP_HOOKS=1` to get past the red local gate.

## Symptoms

```
FAIL src/hooks/useDownloadPdf.test.tsx
  TypeError: localStorage.clear is not a function
   ❯ src/hooks/useDownloadPdf.test.tsx:88  (beforeEach)

FAIL src/hooks/useAnalyzedResume.test.tsx
  TypeError: Cannot read properties of undefined (reading 'unmount')
   ❯ src/hooks/useAnalyzedResume.test.tsx:46  act(() => root.unmount())
```

## Root-cause investigation

- Both files declare `// @vitest-environment jsdom` and call `localStorage.clear()` in `beforeEach`.
- **Sibling jsdom-pragma hook tests pass** (`useReplaceResumeOnDrop.test.tsx` 9/9 green, same `createRoot`/`act` probe pattern) — so the jsdom environment is applied globally; this is **not** a blanket env-config break.
- The differentiator: these two are the **only** jsdom hook suites that touch `localStorage`. `localStorage.clear is not a function` means a `localStorage` global exists but is not a real `Storage`.
- Cascade: `localStorage.clear()` throws in `beforeEach` → the module-scoped `root` is never assigned → `afterEach`/`unmount()` then dereferences `undefined.unmount`, producing the second error class in `useAnalyzedResume`.

**Leading hypothesis:** a non-jsdom `localStorage` global (e.g. Node's experimental Web Storage global) is shadowing jsdom's `window.localStorage`, so `.clear`/`.setItem` are absent. Needs confirmation of the local Node version vs CI.

## Open question — is CI red too?

`main` is the deployed branch, so CI `verify` presumably passes — meaning this is **local-environment-specific** (Node version / experimental flag), not main-is-broken. Worth confirming: if CI is also skipping or these were merged red (they were introduced by #353, `feat(epic): … blank-resume authoring`), the gap is real.

## Fix directions

1. Make the two suites provision their own `Storage` (jsdom `window.localStorage`, or a small `beforeEach` polyfill / `vi.stubGlobal('localStorage', ...)`), instead of assuming a working global.
2. Or pin the vitest jsdom environment so the Node experimental `localStorage` global cannot shadow `window.localStorage`.
3. Confirm the Node version the local hook runs under and whether CI matches.

## Repro

```
git switch main && git pull
npx vitest run src/hooks/useAnalyzedResume.test.tsx src/hooks/useDownloadPdf.test.tsx
# → 13 failed
```

Introduced by: #353 (56a20d8).

**Comment by s-annam** [comment]
## Implementation Complete — `bbfb442`

Fixed on PR #397 (`gh-396-result-page-guardrails`) — folded in so the branch verifies green end-to-end rather than sequencing a separate PR.

### Fix directions (from the issue)

- [x] **Suites provision their own working `Storage`** — new shared helper `src/hooks/__test-utils__/memory-storage.ts` exports `installMemoryLocalStorage()`, which assigns a fresh in-memory `Storage` to `globalThis.localStorage` in `beforeEach`. Wired into `useAnalyzedResume.test.tsx` + `useDownloadPdf.test.tsx` (the two failing suites).
- [x] **Node version confirmed vs CI** — root cause reproduced on local **Node 25.9.0**; CI runs **Node 20** (no native global `localStorage`), which is why CI was green while local `verify` was red. Confirmed `globalThis.localStorage === window.localStorage` with `.clear` undefined — Node's broken native global shadows jsdom's.
- [ ] **Pin the vitest jsdom env instead (direction 2)** — not taken; the per-suite shim is the minimal, convention-matching fix (matches the existing `MemoryStorage` pattern already in `useModelSelection.test.ts`) and avoids touching `vite.config.ts` / global setup.

### Additional Changes

- **DRY / fallow**: extracted the shim from the pre-existing copy in `useModelSelection.test.ts` (removed the local dup, now imports the shared helper) so a second/third copy wouldn't trip fallow's duplication gate. `MemoryStorage` class kept module-private; only `installMemoryLocalStorage()` exported (avoids unused-export flag).
- **Consistency**: `useModelSelection.integration.test.tsx` switched from the Node-version-fragile `globalThis.localStorage?.clear?.()` no-op to the shared helper.
- **Verification**: full `npm run test` → **1673 passed, 3 skipped** (was 13 failing); typecheck + lint clean; CI `verify` green (run 28912727231).
- PR #397 body updated with `Resolves #398`.

**Comment by s-annam** [comment]
Another site hit this: PR #402 (docs/skill-only, `skill-milestone-depfix`) had to push with `RESUMELINT_SKIP_HOOKS=1` — same 13 failures, same `localStorage.clear is not a function` / `undefined.unmount` cascade, on a diff that touches zero source (only `.claude/skills/*.md`). Reinforces the root cause here: it's environment-global, not diff-related, and it's now blocking unrelated PRs from clean pre-push. Bumps the priority on Fix direction 1/2 (provision a real `Storage` in the two suites, or pin the jsdom env so Node's experimental `localStorage` can't shadow `window.localStorage`).

**Comment by s-annam** [comment]
Fix already exists on **PR #397** (`gh-396-result-page-guardrails`), unmerged. It implements Fix direction 1 exactly:

- New `src/hooks/__test-utils__/memory-storage.ts` — `installMemoryLocalStorage()` sets a fresh in-memory `Storage` on `globalThis.localStorage` per test. Its doc comment cites this issue and the Node-20-CI-green / Node-25-local-red split named here.
- Both failing suites swap the `beforeEach` `localStorage.clear()` → `installMemoryLocalStorage()`: `useAnalyzedResume.test.tsx` (9) and `useDownloadPdf.test.tsx` (4) — all 13.

Directly kills `localStorage.clear is not a function` and its downstream `undefined.unmount` cascade. **Merging #397 closes this** — no separate fix needed. Until then `main` stays red locally on Node 22+ and unrelated PRs keep pushing with `RESUMELINT_SKIP_HOOKS=1` (e.g. #402).
